[package]
name = "passdf"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.5.0"
clap = { version = "4.5.54", features = ["derive"] }
num_cpus = "1.17.0"
tokio = {version = "1.49.0", features = ["full"]}
